NETWORK=testnet_aurora
INCREMENTER_ADDRESS=

deploy:
	yarn hardhat run scripts/deploy.js --network $(NETWORK)

decMul:
	yarn hardhat decMul --network $(NETWORK) --deployment-address $(DEPLOYMENT_ADDRESS)
